version: '3.8'

services:
  app:
    image: kavin2002/springbootapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2008:2008"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ust1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ust1
      MYSQL_ROOT_PASSWORD: pass@word1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: