version: 2.1

jobs:
  build-and-push-docker-image:
    docker:
      - image: cimg/openjdk:17.0  # CircleCI-maintained image with Java 17

    steps:
      - checkout

      - run:
          name: Build with Maven
          command: mvn clean package -DskipTests  # Build the jar file without running tests

      - setup_remote_docker:
          version: 20.10.7  # Use a remote Docker daemon to build and push images

      - run:
          name: Build Docker Image
          command: docker build -t kavin2002/sampleimg:${CIRCLE_SHA1} .  # Build Docker image with commit hash as tag

      - run:
          name: Login to Docker Hub
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - run:
          name: Push Docker Image
          command: docker push kavin2002/sampleimg:${CIRCLE_SHA1}  # Push Docker image to Docker Hub

workflows:
  build-and-push-workflow:
    jobs:
      - build-and-push-docker-image
